# -*- coding: utf-8 -*-
"""AI_BOT_fixed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oTBMM4StdehBOWw_a3l48MUmPrWe2OFO
"""

import torch

if torch.cuda.is_available():
    print(f"GPU is active! Device name: {torch.cuda.get_device_name(0)}")
else:
    print("GPU is NOT active. Please change your runtime type.")

# 1. Install Unsloth and dependencies
!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps trl peft accelerate

import pandas as pd
import json
from google.colab import drive
from unsloth import FastLanguageModel
import torch
from trl import SFTTrainer
from transformers import TrainingArguments
from datasets import load_dataset
import warnings
import logging
from transformers import utils

# 1. Suppress standard Python & Deprecation warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)

# 2. Suppress Hugging Face/Transformers logging clutter
utils.logging.set_verbosity_error()
logging.getLogger("transformers").setLevel(logging.ERROR)

from unsloth.chat_templates import train_on_responses_only

drive.mount('/content/drive')

"""Load a base model

We will use Llama-3.2-3B-Instruct.

Why: It is natively trained to understand conversational turns (user vs assistant), fits easily into a free Google Colab T4 GPU for training, and can be run locally on almost any modern laptop once quantized.
"""

# 2. Load the base model and tokenizer
max_seq_length = 2048 # Supports long interview conversations
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Llama-3.2-1B-Instruct",
    max_seq_length = max_seq_length,
    load_in_4bit = True, # Critical for fitting on a free T4 GPU
)

"""Import Excel file which has all the training data for fine tuning
Here we are loading our data into pandas and then converting to a json format for training purpose
"""

test_messages = [
    {"role": "system", "content": "You are a professional technical interviewer. Current Domain: IMS. Difficulty Level: Hard. Ask probing follow-up questions one at a time."},
    {"role": "user", "content": "I have performed IMS log analysis and testing"}
]

# Test base model BEFORE training
# NOTE: for_inference is used here only for the pre-training test
FastLanguageModel.for_inference(model)

# Format using the model's native chat template
inputs = tokenizer.apply_chat_template(
    test_messages,
    tokenize = True,
    add_generation_prompt = True,  # Tells the model it is the assistant's turn to speak
    return_tensors = "pt",
).to("cuda")

print("\n--- BASE MODEL OUTPUT (BEFORE TRAINING) ---")
outputs = model.generate(input_ids = inputs, max_new_tokens = 128, use_cache = True)
# Decode and print only the new text generated by the assistant
print(tokenizer.decode(outputs[0][inputs.shape[1]:], skip_special_tokens = True))
print("-------------------------------------------\n")

# 3. Setup LoRA (Parameter-Efficient Fine-Tuning)
# Must be called AFTER the base model test and BEFORE training
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,                    # Increased from 8 for better capacity
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
)

# Load your filled-out Excel file
file_path = '/content/drive/MyDrive/Colab Notebooks/Capstone_Interview/Final_300_IMS_Training_Dataset.xlsx'
df = pd.read_excel(file_path)

# Open a new .jsonl file to write to
with open("final_training_data.jsonl", "w") as f:
    for index, row in df.iterrows():
        # Map the Excel columns back to the required JSON structure
        json_object = {
            "category": str(row["Category"]),
            "difficulty": str(row["Difficulty"]),
            "messages": [
                {"role": "system", "content": str(row["System_Message"])},
                {"role": "user", "content": str(row["User_Message"])},
                {"role": "assistant", "content": str(row["Assistant_Message"])}
            ]
        }

        # Write each row as a new JSON line
        f.write(json.dumps(json_object) + "\n")

print("Conversion complete! final_training_data.jsonl is ready for Colab.")

# 4. Load your conversational dataset
dataset = load_dataset("json", data_files="final_training_data.jsonl", split="train")

def format_chat_template(examples):
    # This applies Llama 3's native chat template to our "messages" array
    # It converts the JSON into the exact <|start_header_id|> format Llama expects
    texts = [tokenizer.apply_chat_template(convo, tokenize=False, add_generation_prompt=False) for convo in examples["messages"]]
    return {"text": texts}

# Apply the formatting to the entire dataset
dataset = dataset.map(format_chat_template, batched=True)

# 5. Configure the Trainer
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    packing = False,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        num_train_epochs = 1,
        learning_rate = 2e-4,      # Fixed: was 5e-5 (too low), 2e-4 is the Unsloth/LoRA standard
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        output_dir = "outputs",
        save_strategy = "no",
    ),
)

# *** KEY FIX: Train only on assistant responses, not on the system/user prompt ***
# Without this, the model learns to predict EVERY token (system + user + assistant),
# causing it to repeat the input instead of generating new responses.
# This masks the loss so only the assistant's reply tokens are trained on.
trainer = train_on_responses_only(
    trainer,
    instruction_part = "<|start_header_id|>user<|end_header_id|>\n\n",
    response_part    = "<|start_header_id|>assistant<|end_header_id|>\n\n",
)

# 6. Run the training
trainer_stats = trainer.train()

FastLanguageModel.for_inference(model)

# Re-encode the test prompt (inputs may have been freed after training)
inputs = tokenizer.apply_chat_template(
    test_messages,
    tokenize = True,
    add_generation_prompt = True,
    return_tensors = "pt",
).to("cuda")

print("\n--- TUNED MODEL OUTPUT (AFTER TRAINING) ---")
outputs = model.generate(input_ids = inputs, max_new_tokens = 128, use_cache = True)
print(tokenizer.decode(outputs[0][inputs.shape[1]:], skip_special_tokens = True))
print("-------------------------------------------\n")

# 7. Save and export to GGUF
model.save_pretrained_gguf(
    "interview_model",
    tokenizer,
    quantization_method = "q4_k_m",
)

# Copy the GGUF folder to your Google Drive
!cp -r interview_model_gguf "/content/drive/MyDrive/Colab Notebooks/Capstone_Interview/"

# Copy the 16-bit base model folder to your Google Drive
!cp -r interview_model "/content/drive/MyDrive/Colab Notebooks/Capstone_Interview/"

"""# RAG IMPLEMENTATION"""

!pip install -q faiss-cpu langchain langchain-community pypdf sentence-transformers

import os
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings.sentence_transformer import SentenceTransformerEmbeddings
from langchain_community.vectorstores import FAISS

# Define distinct storage paths for FAISS
RESUME_DB_DIR = "./faiss_db/resume"
DOMAIN_DB_DIR = "./faiss_db/domain"

print("Loading embedding model...")
embedding_function = SentenceTransformerEmbeddings(model_name="all-MiniLM-L6-v2")

def ingest_document(pdf_path, target_db):
    if not os.path.exists(pdf_path):
        return f"Error: File {pdf_path} not found."

    loader = PyPDFLoader(pdf_path)
    documents = loader.load()

    # We use different chunking strategies based on the document type
    if target_db == 'resume':
        chunk_size = 400
        chunk_overlap = 50
        persist_dir = RESUME_DB_DIR
    elif target_db == 'domain':
        chunk_size = 1000
        chunk_overlap = 150
        persist_dir = DOMAIN_DB_DIR
    else:
        return "Invalid target DB."

    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        separators=["\n\n", "\n", ".", " "]
    )
    chunks = text_splitter.split_documents(documents)

    # Using FAISS instead of ChromaDB
    db = FAISS.from_documents(chunks, embedding_function)
    db.save_local(persist_dir)

    print(f"✅ Successfully ingested {pdf_path} into the {target_db.upper()} database ({len(chunks)} vectors).")
    return db

RESUME_FILE = "my_resume.pdf"
DOMAIN_FILE = "ims_telecom_specs.pdf"

print("--- Processing Resume ---")
resume_db = ingest_document(RESUME_FILE, target_db="resume")

print("\n--- Processing Domain Knowledge ---")
domain_db = ingest_document(DOMAIN_FILE, target_db="domain")

"""# Combine the both"""

from langchain_community.vectorstores import FAISS

# Connect to the local FAISS databases
# allow_dangerous_deserialization is required to load local FAISS index files
resume_vectorstore = FAISS.load_local(RESUME_DB_DIR, embedding_function, allow_dangerous_deserialization=True)
domain_vectorstore = FAISS.load_local(DOMAIN_DB_DIR, embedding_function, allow_dangerous_deserialization=True)

def get_interviewer_response(candidate_latest_message, previous_question):
    """
    1. Fetches facts from Domain DB to check the candidate's answer.
    2. Fetches background from Resume DB to guide the next question.
    """

    # Step 1: Fact Retrieval (To verify the candidate's answer)
    search_query = f"{previous_question} {candidate_latest_message}"
    domain_docs = domain_vectorstore.similarity_search(search_query, k=2)
    domain_context = "\n---\n".join([doc.page_content for doc in domain_docs])

    # Step 2: Persona Retrieval (To ask the next tailored question)
    resume_docs = resume_vectorstore.similarity_search(candidate_latest_message, k=2)
    resume_context = "\n---\n".join([doc.page_content for doc in resume_docs])

    # Step 3: Prompt Construction
    system_prompt = f"""You are a strict, professional technical interviewer. Current Domain: IMS. Difficulty Level: Hard.

    YOUR TASK:
    1. Evaluate the candidate's previous answer using the DOMAIN FACTS. (If they are wrong, politely correct them without giving away the full answer).
    2. Ask ONE probing follow-up question based on their RESUME BACKGROUND. Do not ask multiple questions at once.

    === DOMAIN FACTS (Use this to verify their answer) ===
    {domain_context}

    === CANDIDATE RESUME BACKGROUND (Use this to ask the next question) ===
    {resume_context}
    """

    return system_prompt

# Simulate a mid-interview exchange about VoLTE
previous_interviewer_question = "Can you explain how a dedicated bearer is established during a VoLTE call?"
candidate_answer = "The network sends a SIP INVITE to set up the QCI 1 bearer."

# Run the RAG orchestration
constructed_prompt = get_interviewer_response(
    candidate_latest_message=candidate_answer,
    previous_question=previous_interviewer_question
)

print("=== WHAT THE LLM WILL SEE IN THE SYSTEM PROMPT ===")
print(constructed_prompt)

"""# The Unified Gradio Chat Interface"""

import gradio as gr
import torch
import time
from transformers import AutoModelForCausalLM, AutoTokenizer
from langchain_community.vectorstores import FAISS

# ==========================================
# 1. LOAD THE FINE-TUNED MODEL
# ==========================================
print("Loading Fine-Tuned Model into GPU...")
MODEL_PATH = "interview_model"

tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_PATH,
    torch_dtype=torch.float16,
    device_map="auto"
)

# ==========================================
# 2. RESUME INGESTION & TIMER VARIABLES
# ==========================================
INTERVIEW_TIME_LIMIT = 15 * 60 # 15 minutes in seconds

def process_uploaded_resume(pdf_file):
    if pdf_file is None:
        return "⚠️ Please upload a PDF file."
    try:
        ingest_document(pdf_file.name, target_db="resume")
        global resume_vectorstore
        resume_vectorstore = FAISS.load_local(RESUME_DB_DIR, embedding_function, allow_dangerous_deserialization=True)
        return "✅ Resume successfully processed and loaded into active memory! You can now switch to the Interview tab."
    except Exception as e:
        return f"❌ Error processing resume: {str(e)}"

# ==========================================
# 3. CHAT & EVALUATION LOGIC
# ==========================================
def respond(user_message, history, start_time):
    """Handles the chat and checks the 15-minute timer."""
    # 1. Start the timer on the very first message
    if start_time is None:
        start_time = time.time()
        previous_question = "We are beginning the technical interview. What is your background?"
    else:
        # Check if 15 minutes have passed
        elapsed_time = time.time() - start_time
        if elapsed_time > INTERVIEW_TIME_LIMIT:
            timeout_msg = "⏳ **The 15-minute time limit has expired.** The interview is now concluded. Please click 'End Interview & Score Candidate'."
            history.append((user_message, timeout_msg))
            # Return updated history, the start time, clear the input box, and disable the input box
            return history, start_time, "", gr.update(interactive=False, placeholder="Interview Ended.")

        previous_question = history[-1][1]

    # 2. Run the RAG logic
    system_prompt = get_interviewer_response(candidate_latest_message=user_message, previous_question=previous_question)

    messages = [{"role": "system", "content": system_prompt}]
    for human_text, assistant_text in history:
        messages.append({"role": "user", "content": human_text})
        messages.append({"role": "assistant", "content": assistant_text})

    messages.append({"role": "user", "content": user_message})

    inputs = tokenizer.apply_chat_template(messages, tokenize=True, add_generation_prompt=True, return_tensors="pt").to("cuda")

    with torch.no_grad():
        outputs = model.generate(
            input_ids=inputs, max_new_tokens=150,
            eos_token_id=tokenizer.eos_token_id, pad_token_id=tokenizer.eos_token_id
        )

    response_text = tokenizer.decode(outputs[0][inputs.shape[1]:], skip_special_tokens=True)
    history.append((user_message, response_text))

    return history, start_time, "", gr.update()

def evaluate_interview(history):
    """Takes the entire chat history and asks the LLM to score the candidate."""
    if not history:
        return "No interview data to evaluate."

    # Format the transcript
    transcript = ""
    for user_msg, bot_msg in history:
        transcript += f"Candidate: {user_msg}\nInterviewer: {bot_msg}\n\n"

    # Create a new prompt telling the model to act as a recruiter grading the transcript
    eval_prompt = f"""You are a Senior Technical Recruiter. Review the following technical interview transcript.
    Evaluate the candidate's technical accuracy, depth of knowledge, and problem-solving skills.

    TRANSCRIPT:
    {transcript}

    Provide your response strictly in the following format:
    SCORE: [Give a rating from 1 to 10]
    FEEDBACK: [Provide a 2-3 sentence justification for the score]
    """

    messages = [{"role": "user", "content": eval_prompt}]
    inputs = tokenizer.apply_chat_template(messages, tokenize=True, add_generation_prompt=True, return_tensors="pt").to("cuda")

    with torch.no_grad():
        outputs = model.generate(input_ids=inputs, max_new_tokens=250, eos_token_id=tokenizer.eos_token_id, pad_token_id=tokenizer.eos_token_id)

    evaluation = tokenizer.decode(outputs[0][inputs.shape[1]:], skip_special_tokens=True)
    return evaluation

# ==========================================
# 4. LAUNCH THE CUSTOM UI
# ==========================================
print("Launching User Interface...")

with gr.Blocks(title="AI Technical Interviewer Hub", theme="soft") as demo:
    gr.Markdown("# 🤖 AI Technical Interviewer Dashboard")

    with gr.Tab("📁 Step 1: Upload Resume"):
        gr.Markdown("### Candidate Ingestion")
        file_input = gr.File(label="Upload Candidate Resume (PDF only)", file_types=[".pdf"])
        upload_button = gr.Button("Process & Index Resume", variant="primary")
        status_output = gr.Textbox(label="System Status", interactive=False)
        upload_button.click(fn=process_uploaded_resume, inputs=[file_input], outputs=[status_output])

    with gr.Tab("💬 Step 2: Conduct Interview"):
        # State variables to hold chat history and the start time
        chat_history = gr.State([])
        start_time = gr.State(None)

        # Custom layout
        with gr.Row():
            with gr.Column(scale=3):
                chatbot = gr.Chatbot(label="Interview Chat", height=500)
                user_input = gr.Textbox(show_label=False, placeholder="Type your answer and press Enter...", lines=2)

            with gr.Column(scale=1):
                gr.Markdown("### Interview Controls")
                end_button = gr.Button("🛑 End Interview & Score Candidate", variant="stop")
                score_output = gr.Textbox(label="Final Evaluation", lines=15, interactive=False, placeholder="Score will appear here...")

        # When the user presses Enter in the text box
        user_input.submit(
            fn=respond,
            inputs=[user_input, chat_history, start_time],
            outputs=[chatbot, start_time, user_input, user_input] # The last output updates the textbox state
        )

        # When the End Interview button is clicked
        end_button.click(
            fn=evaluate_interview,
            inputs=[chatbot],
            outputs=[score_output]
        ).then(
            # Disable the chat input box after clicking end
            fn=lambda: gr.update(interactive=False, placeholder="Interview Ended. See score on the right."),
            inputs=[],
            outputs=[user_input]
        )

# Launch the app
demo.launch(share=True, debug=True)